# Generated by Django 4.0.3 on 2022-03-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='eligible',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='getting',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
