# Generated by Django 4.0.3 on 2022-03-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0002_details_eligible_details_getting'),
    ]

    operations = [
        migrations.CreateModel(
            name='NSAP_deatils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sl_No', models.IntegerField()),
                ('District', models.CharField(max_length=50)),
                ('Scheme', models.CharField(max_length=15)),
                ('Total_Beneficiary', models.IntegerField()),
                ('Total_Bank', models.IntegerField()),
                ('Total_PO', models.IntegerField()),
                ('Total_MO', models.IntegerField()),
                ('Total_Cash', models.IntegerField()),
                ('Total_Aadhar', models.IntegerField()),
                ('Verified', models.IntegerField()),
                ('Verified_Aadhar_with_bank', models.IntegerField()),
                ('PFMS_Registered', models.IntegerField()),
                ('State', models.CharField(max_length=70)),
            ],
        ),
        migrations.DeleteModel(
            name='details',
        ),
    ]
